# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/demo/others/verilog/cpu54_single/cpu54_single.cache/wt [current_project]
set_property parent.project_path E:/demo/others/verilog/cpu54_single/cpu54_single.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files e:/demo/others/verilog/cpu54_single/cpu54_single.srcs/sources_1/ip/mips_54_mars_simulate_student_ForWeb.coe
add_files -quiet e:/demo/others/verilog/cpu54_single/cpu54_single.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp
set_property used_in_implementation false [get_files e:/demo/others/verilog/cpu54_single/cpu54_single.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp]
read_mem E:/demo/others/verilog/cpu54_single/cpu54_single.srcs/sources_1/imports/behav/infile.dat
read_verilog -library xil_defaultlib {
  E:/demo/others/verilog/cpu54_single/cpu54_single.srcs/sources_1/imports/cpu31_test.srcs/sources_1/new/dff32.v
  E:/demo/others/verilog/cpu54_single/cpu54_single.srcs/sources_1/imports/cpu31_test.srcs/sources_1/new/sccpu_control.v
  E:/demo/others/verilog/cpu54_single/cpu54_single.srcs/sources_1/imports/cpu31_test.srcs/sources_1/imports/Desktop/alu.v
  E:/demo/others/verilog/cpu54_single/cpu54_single.srcs/sources_1/imports/cpu31_test.srcs/sources_1/imports/Desktop/regfile.v
  E:/demo/others/verilog/cpu54_single/cpu54_single.srcs/sources_1/imports/cpu31_test.srcs/sources_1/new/extend.v
  E:/demo/others/verilog/cpu54_single/cpu54_single.srcs/sources_1/imports/others/DIVU.v
  E:/demo/others/verilog/cpu54_single/cpu54_single.srcs/sources_1/imports/others/DIV.v
  E:/demo/others/verilog/cpu54_single/cpu54_single.srcs/sources_1/imports/Desktop/mux.v
  E:/demo/others/verilog/cpu54_single/cpu54_single.srcs/sources_1/imports/cpu31_test.srcs/sources_1/new/cpu.v
  E:/demo/others/verilog/cpu54_single/cpu54_single.srcs/sources_1/imports/cpu31_test.srcs/sources_1/new/dmem.v
  E:/demo/others/verilog/cpu54_single/cpu54_single.srcs/sources_1/imports/cpu31_test.srcs/sources_1/new/sccomp_dataflow.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top sccomp_dataflow -part xc7a100tcsg324-1


write_checkpoint -force -noxdef sccomp_dataflow.dcp

catch { report_utilization -file sccomp_dataflow_utilization_synth.rpt -pb sccomp_dataflow_utilization_synth.pb }
